=== coppolam/swarmulator/conf/parameters.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="parameters_t">
    <xs:sequence>
      <xs:element name="simulation_updatefreq" type="xs:float"/>
      <xs:element name="simulation_realtimefactor" type="xs:float"/>
	    <xs:element name="window_width" type="xs:integer"/>
      <xs:element name="window_height" type="xs:integer"/>
      <xs:element name="scale" type="xs:float"/>
      <xs:element name="mouse_drag_speed" type="xs:float"/>
      <xs:element name="mouse_zoom_speed" type="xs:float"/>
      <xs:element name="zoom" type="xs:float"/>
      <xs:element name="animation_updatefreq" type="xs:float"/>
      <xs:element name="visible_centroid" type="xs:integer"/>
      <xs:element name="logger_updatefreq" type="xs:integer"/>
      <xs:element name="time_limit" type="xs:float"/>
      <!-- xs:element name="parameter_name" type="xs:parametertype"/-->
    </xs:sequence>
  </xs:complexType>

  <xs:element name="parameters" type="parameters_t"/>

</xs:schema>

=== coppolam/swarmulator/conf/parameters.xml
<?xml version="1.0"?>
<parameters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="parameters.xsd">
  <!-- Simulation -->
  <simulation_updatefreq>20</simulation_updatefreq>
  <simulation_realtimefactor>50</simulation_realtimefactor>
  <time_limit>0</time_limit>
  <!-- (seconds). Use time_limit > 0 to set a limit -->
  <environment>square</environment>
  <!-- See the folder conf/environments/ for available environments. 
       Create your own or use "random" to generate a random map at runtime -->
  <!-- Animation -->
  <window_width>800</window_width>
  <window_height>800</window_height>
  <scale>0.2</scale>
  <mouse_drag_speed>0.3</mouse_drag_speed>
  <mouse_zoom_speed>0.5</mouse_zoom_speed>
  <zoom>-70</zoom>
  <!-- Start up zoom, bounded -90 and 9 -->
  <animation_updatefreq>25</animation_updatefreq>
  <!-- Logger -->
  <logger_updatefreq>1</logger_updatefreq>
  <!-- Additional parameters -->
  <policy>../swarmulator/conf/state_action_matrices/aggregation_policy_test.txt</policy>
  <!-- <sequential_interval>5</sequential_interval> -->
  <!--new_parameter_name>default value</new_parameter_name-->
</parameters>
